### ISSUE TITLE
Requests are executed twice, breaking unique rules

### ISSUE THREAD

**Issue by captnCC** [hotmeteor/spectator#118]
I started to adopt the package in a project that requires an unique handle per user. While testing the create api call against my spec it always errored out with a 422, because the handle wasn't unique.

Turns out, that the request was executed twice on behalf of the `Middleware`. Once on line 64 and the second time in the `validate` method if a spec was loaded. 
Is this a bug or a feature? 🤔
Removing the second execution seems to fix the problem and my test succeed.

**Comment by joshuafranks** [comment]
I've addressed this issue in #113, just pending approval from the maintainers 👍

**Comment by hotmeteor** [comment]
Resolved in https://github.com/hotmeteor/spectator/pull/113
