### ISSUE TITLE
middleware should return 422?

### ISSUE THREAD

**Issue by jarrodparkes** [hotmeteor/spectator#13]
I have a spec that describes a `POST /v1/login` endpoint expecting a request body like this:

```json
{
    "email": "john.doe@example.com",
    "password": "12345678"
}
```

Here's a contract test that I've written to confirm this:

```php
public function setUp(): void
{
    parent::setUp();
    Spectator::using('Spec.v1.json');
}

public function test_login()
{
    $response = $this->postJson(route('api.login'), [
        'email' => null,
        'password' => null
    ])->assertStatus(422);
}
```

When Spectacle's middleware takes over, it is transforming the `$response` such that a `400` status code is returned; however, this is impossible from a Laravel perspective. Laravel would always return a `422` in this case, even if the request body was dropped all together.

I believe these are the responsible lines of code:

https://github.com/hotmeteor/spectator/blob/master/src/Middleware.php#L36

Perhaps changing `400` to `422` solves this?

**Comment by hotmeteor** [comment]
Your test is combining both a feature and a spec test. Try changing it to:
```php
public function test_login()
{
    $response = $this->postJson(route('api.login'), [
        'email' => null,
        'password' => null
    ])
        ->assertValidRequest()
        ->assertValidResponse(422);
}
```
The test should be testing the structure of the request and response that adheres to the response code.

The `400` code is Spectator's code for invalid structure, not Laravel's code for invalid data.

**Comment by jarrodparkes** [comment]
@hotmeteor so, when I change the test to match your suggestion, I still get the following error:

```bash
There was 1 failure:

1) Tests\Feature\Api\Auth\ApiLoginControllerTest:: test_login
Request body did not match provided JSON schema.
Failed asserting that true is false.
```

^ Depending on how you want to interpret this, the request body could be said to be invalid/improper/etc:

- "The correct fields are provided, but they null"
- "The correct fields are provided, but the email field should actually look like an email"
- "Since all the fields provided are null, technically, the request body is invalid"

Whatever your interpretation, if you look at the same request, vended through something like Paw/Postman/etc, then you get the 422 that Laravel actually produces:

<img width="1552" alt="Screen Shot 2020-11-23 at 19 52 39" src="https://user-images.githubusercontent.com/1331063/100112214-94873c80-2e34-11eb-88f8-6049451a9aa5.png">

This is the difficulty. I believe that the Spectator middleware is preemptively generating the request body error [here](https://github.com/hotmeteor/spectator/blob/master/src/Validation/RequestValidator.php#L116-L120) even though Laravel would accept the request body and emit a 422.

**Comment by hotmeteor** [comment]
Ya but there's still confusion here.

Spectator isn't even letting you hit the endpoint, because the expected request structure as defined by your spec is incorrect. So it's throwing a 400 first to say "your request is wrong".

Once you fix the request then you'll be able to get through to the endpoint and it'll respond with a `200` or `422` based on the data. At that point you'd have a test for each code.

**Comment by Hasnayeen** [comment]
@hotmeteor even if the expected request structure is provided according to spec it still return `Request body did not match provided JSON schema.`, upon inspection of the code I found the package always return `400` for any validation exception, so there is now way to test for `422`

**Comment by jarrodparkes** [comment]
@hotmeteor correct me if im wrong, but i had a similar problem/misunderstanding.

the `400` which spectator returns for any validation exception is as-designed. if you want to test a 422 response you'll have to do so in a separate, integration-style test (don't call `Spectator::using` at all). this probably isn't too big of an issue considering the structure of 422's across an API are likely similar, so testing its structure (according to spec) wouldn't afford you much after seeing it working for a single endpoint.

**Comment by hotmeteor** [comment]
Ya, that is true, but you _can_ also do a spec test to ensure your `422`-type response has a valid structure.

The issue people are running into I think is that they're attempting to do this with values that are breaking their spec. Here's an example:

Let's say you have a `color` attribute, and the only valid values are "red", "blue", and "yellow". There's a few things to consider here:

1. If you've defined the enum value in your spec for `color` then any value you test will _have_ to match one of those. If not, the spec test will fail with a `400` because it's not adhering to the spec. This isn't a Laravel validation issue, this is a spec issue.
2. If you have not defined the enum, and are willing to accept any string, then you need to pass in a string. If you try to pass in `null` or an integer to test invalid input that is incorrect. You must pass in a string, because that's what your spec declares.
3. In the case of scenario 2, the way you would test this is to pass in an **invalid string**, in the case of our example something like "green" or "banana" or "helicopter". All strings, but none will pass your Laravel validation. This will trigger a `422` response from Laravel, which you can then spec test the structure for.

Does that help?

**Comment by jarrodparkes** [comment]
@hotmeteor i think that helps, yes. it is probably helpful to state that while at least one of the scenarios allows you to test a 422 response, you won't ever be able to get full coverage of the surface area of requests that could cause a 422. for example, if you take your first scenario:

1. If you've defined the enum value in your spec for color ["red", "blue", or "yellow"] then any value you test will have to match one of those. If not, the spec test will fail with a 400 because it's not adhering to the spec. This isn't a Laravel validation issue, this is a spec issue.

And someone was to make the request with the color "purple". While spectator returns a 400 because this doesn't adhere to the spec, a real end-to-end request with the same color "purple" (not plumbed through spectator) would return a 422.

So there is only a certain _class_ of 422 scenarios that spectator can help validate the response structure for

**Comment by hotmeteor** [comment]
Yep, absolutely. But again just to make sure it's clear: spec tests are not intended to test those scenarios. They are intended to test request and response structures. So if you want to test a 422 structure then you'll need to be able to expose that somehow.

Your feature/unit tests can test validation.

**Comment by jarrodparkes** [comment]
right. i think we are on the same page. i believe the confusion boils down to the following assumptions:

- "Sweet! I can use Spectator to test request and response structures! Let me test a 422."
- _(proceeds to make an API request that would normally return a 422)_
- "Wait a minute, this should return a 422! Why is it returning a 400?"_
- _(learns that Spectator is causing the 400 because the request isn't matching the spec)_
- "But, I thought Spectator could validate my responses? I mean "yes" the spec says this, but I didn't know it was going to strictly enforce it with Spectator. The concrete API could still accept this request... hmm"_
- _(reads more documentation)_
- "Oh, so it works in some scenarios and not others."

and from here either they are starting to _get it_. or, they may still be a little confused.

that's my guess.

**Comment by Hasnayeen** [comment]
> Ya, that is true, but you _can_ also do a spec test to ensure your `422`-type response has a valid structure.
> 
> The issue people are running into I think is that they're attempting to do this with values that are breaking their spec. Here's an example:
> 
> Let's say you have a `color` attribute, and the only valid values are "red", "blue", and "yellow". There's a few things to consider here:
> 
>     1. If you've defined the enum value in your spec for `color` then any value you test will _have_ to match one of those. If not, the spec test will fail with a `400` because it's not adhering to the spec. This isn't a Laravel validation issue, this is a spec issue.
> 
>     2. If you have not defined the enum, and are willing to accept any string, then you need to pass in a string. If you try to pass in `null` or an integer to test invalid input that is incorrect. You must pass in a string, because that's what your spec declares.
> 
>     3. In the case of scenario 2, the way you would test this is to pass in an **invalid string**, in the case of our example something like "green" or "banana" or "helicopter". All strings, but none will pass your Laravel validation. This will trigger a `422` response from Laravel, which you can then spec test the structure for.
> 

I just tested this scenario in my project, I have an enum field in my request and provided a value that is not in the spec, all the other field is provided according to spec, but it is still returning `400`. So even in this way I can't spec test 422 response (I'm not testing validation message but rather 422 response structure);

**Comment by bilfeldt** [comment]
Dear @hotmeteor 

I have not been able to confirm this in the source code, but when first defining the specs using something like `Spectator::using('Api.v1.json')` and afterwards posting json (using `$this->postJson($uri, $data)`) then this package intercepts the request and validates against the specs?

Hence this is why an invalid request (like an incorrect `color` for an enum field - case 1 in your [comment](https://github.com/hotmeteor/spectator/issues/13#issuecomment-736596040) above) would return a status code of 400 like so right:

```php
<?php

use Spectator/Spectator;

class ExampleTest extends TestCase
{
    public function testValidationException()
    {
        Spectator::using('Api.v1.json');

        $response = $this->postJson('/example', ['color' => 'green']); // This is an invalid value and the specs has enum values: "red", "blue", and "yellow"

        // $response->getStatusCode(); // 400
        // $response->getContent(); // {"exception":"Spectator\\Exceptions\\RequestValidationException","message":"Request body did not match provided JSON schema.","errors":"[\n    {}\n]\n"}

        $response
            ->assertValidRequest() // This is clearly false
            ->assertValidResponse(422); // The 422 response should be valid since this is also defined in the api specs
    }
}
```

My question is if it would not be better to only test the request against the specs when running `$response->assertValidRequest()`? That way it would be possible to make an invalid request and check the response alone like so:

```php
<?php

use Spectator/Spectator;

class ExampleTest extends TestCase
{
    public function testValidationException()
    {
        Spectator::using('Api.v1.json');

        $response = $this->postJson('/example', ['color' => 'green']); // This is an invalid value and the specs has enum values: "red", "blue", and "yellow"

        // $response->getStatusCode(); // 422
        // $response->getContent(); // {"message":"The given data was invalid.","errors":{"color":["The selected color is invalid."]

        $response
            // ->assertValidRequest() // note that we are NOT checking for a valid request since we are deliberately making an invalid request
            ->assertValidResponse(422); // The 422 response should be valid since this is also defined in the api specs
    }
}
```

The above was created using something like:

```php
Validator::make(['color' => 'green'], [
    'color' => 'in:red,blue,yellow',
])->validate();
```

**Comment by ronaldwanink** [comment]
Closed issue, but since this confused me already several times: (ref https://laracasts.com/discuss/channels/laravel/any-good-ideas-on-what-to-do-next).

Analysing a 422 and then having test failures on all kind of places with 400's is really confusing. Also I get frequently "incorrectly nested style tag" error with it, so my console seems to struggle also with it.
