### ISSUE TITLE
'additionalProperties' are not supported by Spectator?

### ISSUE THREAD

**Issue by Marre-86** [hotmeteor/spectator#143]
I've got this in my OpenAPI spec:
```
    CartResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/CartItem'
        message:
          type: string
```

And the tests using Spectator pass though they must fall because I introduce an error into specs for testing purposes (in CartItem object replace one of its properties type to 'integer' from 'string')

Moreover, even if I replace **$ref:** value with totally another object the tests pass nevertheless!

**Comment by ronaldwanink** [comment]
FYI: I use `additionalProperties=true/false`, and that works fine.
