### ISSUE TITLE
Is there a way to enable/disable Spectator  for some API calls while testing?

### ISSUE THREAD

**Issue by ronaldwanink** [hotmeteor/spectator#144]
I have some API calls that are not documented, and find these hard to test with Spectator.
It used to work using v1.7.1 but after upgrading to Laravel 10 I get `Undefined variable $response` .

Adding the suggested `return $response ?? null;` to the Middleware.php of course does not work, I want to skip the test, not get the (clearer) MissingSpecException which undoubtedly will be happening.

Is there a way to switch off Spectator testing for some calls?
I am explicitly not trying to validate request or response structures in my test code, it is the HTTP POST that causes issues with the latest version.

**Comment by ronaldwanink** [comment]
Hmm.. reading [110]( https://github.com/hotmeteor/spectator/pull/110) this should not happen?

Let me do some more diggin'

**Comment by rpetre** [comment]
I have a similar problem: I'm trying to call in my test a route that's covered by a different spec that was loaded via Spectator::setPathPrefix and the middleware complains it doesn't know about it.

I can't figure out a simple way to disable Spectator for that particular request, but it would be useful to be able to put it in "transparent mode" (probably raising an exception if some schema assertion is attempted).

Meanwhile I can probably move my call in a different testcase.

**Comment by bastien-phi** [comment]
@ronaldwanink You can call `Spectator::using(null);` before the http call to disable Spectator for the route.
Does it work the way you expected ?

**Comment by bastien-phi** [comment]
Just saw in the codebase, you cal also call `Spectator::reset();` to disable Spectator
