### ISSUE TITLE
integer? <== The data (null) must match the type

### ISSUE THREAD

**Issue by ronaldwanink** [hotmeteor/spectator#145]
I keep on getting issues like `y*: integer? <== The data (null) must match the type: integer` when y is part of an object in an array.

I know [this](https://github.com/hotmeteor/spectator/pull/25) exists, but somehow I cannot get rid of the error. 

Update:

I even get this problem in simple situations (but somehow not always in similar situations):

```
array <== All array items must match schema
    object <== The properties must match schema: product_id
        id*: integer
        product_id: integer? <== The data (null) must match the type: integer
```

(OpenAPI 3.0, Laravel 10, latest build)

**Comment by morcano** [comment]
+1

**Comment by absoftware** [comment]
+1
