### ISSUE TITLE
Unclear error messages when failing to parse spec file

### ISSUE THREAD

**Issue by michaeldyrynda** [hotmeteor/spectator#29]
Sample application: https://github.com/michaeldyrynda/spectator-sample

When the spec file is [invalid](https://github.com/michaeldyrynda/spectator-sample/commit/37db1eb48dd008ba9eccbc3cf6fe90aa9b57fa38), in this instance because the tags are incorrectly defined as:

```yml
tags:
  - "I don't"
  - "know what"
  - "I'm doing"
```

A `TypeErrorException` is thrown within `cebe\openapi\SpecBaseObject@instantiate:161`. Because Laravel's exception handling swallows this, the only feedback provided from the failed test is `Expected status code 200 but received 500.`

[Fixing](https://github.com/michaeldyrynda/spectator-sample/commit/c7ac32c0b507951e51cbe48087a613acd66c55c4) the tags fixes the problem, of course.

```yml
tags:
  - name: "I don't"
  - name: "know what"
  - name: "I'm doing"
```

But it is not clear from the failed test exactly what the issue was, even if using `php artisan test --verbose`. It would be good if these could be explicitly handled, even if that means to broadly catch the parsing exceptions and direct the developer to run it through `spectral` or similar.

```
> spectral lint contract/openapi.yml
OpenAPI 3.x detected

/Users/michael.dyrynda/code/spectator-sample/contract/openapi.yml
 14:5  error  oas3-schema  `0` property type should be object.  tags[0]

✖ 1 problem (1 error, 0 warnings, 0 infos, 0 hints)
```

**Comment by hotmeteor** [comment]
Brilliant, thanks. Agreed about the error handling, and TBH I thought this would have been reported better already. 

I've got some ideas on how to make this better, this was helpful. I'll hack on it this morning.

**Comment by hotmeteor** [comment]
@michaeldyrynda This will update the validation message to instruct developers to run `spectral` on their spec file in this scenario. Is that what you were thinking? 

https://github.com/hotmeteor/spectator/pull/31/files#diff-c8cb7e65bde7d6818e010889c26269555ed33f9e0aad75e9ecb4cfbe891fc139R143
