### ISSUE TITLE
Not respecting disabled exception handling in tests

### ISSUE THREAD

**Issue by beblife** [hotmeteor/spectator#32]
I noticed that when an exception occurs and is caught by [this code](https://github.com/hotmeteor/spectator/blob/77a4cb1e6e636b6a243d9520e1a0d35a5402547a/src/Middleware.php#L49-L51) with exception handling disabled using `$this->disableExceptionHandling()` in a test, the full stacktrace is not shown when using the `assertValidRequest()` or `assertValidResponse()` assertions.

The message states something like: `Expected status code 200 but received 500` which is not very useful.
To get the full output  `Spectator::reset()` needs to be called first.

I think it would be a good idea to respect the disabled exception handling in that case as those exceptions are most likely thrown in the codebase itself, e.g: A missing import, typo's, etc.

**Comment by hotmeteor** [comment]
Makes sense. Are you PRing or should I have a go at it? This PR might be somewhat helpful/related: https://github.com/hotmeteor/spectator/pull/31

**Comment by beblife** [comment]
I can make a PR for it. Thanks for the link!
