### ISSUE TITLE
Call to undefined method Opis\JsonSchema\ValidationResult::getErrors()

### ISSUE THREAD

**Issue by tsterker** [hotmeteor/spectator#46]
It seems there was one code path missed during the [recent upgrade to `opis/json-schema`](https://github.com/hotmeteor/spectator/commit/8d56d2e709f624732e7ea1a737c38ea3772bb866#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R23).

Unfortunately I currently don't have the time to provide a tested PR.

In `RequestValidator@validateParameters`, it's still `getErrors()`:

https://github.com/hotmeteor/spectator/blob/6c215747a154501ada1c6c08593643ec3f3f1eb9/src/Validation/RequestValidator.php#L81

Compared to e.g. `RequestValidator@validateBody`:
https://github.com/hotmeteor/spectator/blob/6c215747a154501ada1c6c08593643ec3f3f1eb9/src/Validation/RequestValidator.php#L121

**Comment by hotmeteor** [comment]
Thanks, just caught that myself. It'll be tagged in a moment.
