### ISSUE TITLE
Request validation not working when using SubstituteBindings middleware

### ISSUE THREAD

**Issue by bastien-phi** [hotmeteor/spectator#53]
After upgrading to version 1.2, all my tests with path parameters fail with error 
```
 ======================================================== 
  Parameter [client] did not match provided JSON schema.  
 ======================================================== 
  ⨯ The data (object) must match the type: string         
 ======================================================== 
 ```
 
 
After some research, it looks like the `Spectator\Middleware` is ran after `Illuminate\Routing\Middleware\SubstitueBindings` so the `$validator` receives the model here https://github.com/hotmeteor/spectator/blob/master/src/Validation/RequestValidator.php#L73
```php
if ($parameter->in === 'path' && $route->hasParameter($parameter->name)) {
    $data = $route->parameters();
    $result = $validator->validate($data[$parameter->name], $jsonSchema); // $data[$parameter->name] is a Model
}
```

Here is a failing test case (I can open a PR with that if you want)
```php
public function test_resolve_route_model_explicit_binding_with_model()
{
    Spectator::using('Test.v1.json');

    Route::bind('user', function() {
        return new TestUser();
    });

    Route::get('/users/{user}', function (TestUser $user) {
        return [
            'id' => 1,
            'name' => 'Jim',
            'email' => 'test@test.test',
        ];
    })->middleware(SubstituteBindings::class)->middleware(Middleware::class);

    $this->getJson('/users/1')
        ->assertValidRequest()
        ->assertValidResponse();
}
```

**Comment by bastien-phi** [comment]
As a workaround we can define `Spectator\Middleware` before `SubstituteBindings` in `$middlewarePriority` of `HttpKernel`

```php
/** @var array<string> */
protected $middlewarePriority = [
    //... 
    \Spectator\Middleware::class,
    \Illuminate\Routing\Middleware\SubstituteBindings::class,
    // ...
];
```

**Comment by beblife** [comment]
Running into the same issue here on a project. 

I think what @bastien-phi is suggesting as a workaround can be achieved using `prependToMiddlewarePriority()` combined with the current `appendMiddlewareToGroup()` [here in the package's service provider](https://github.com/hotmeteor/spectator/blob/master/src/SpectatorServiceProvider.php#L39).

**Comment by hotmeteor** [comment]
Ya, it's funny, I was messing around with this the other day and thought that might become an issue. I'm going to create a branch, can y'all try it out?

**Comment by hotmeteor** [comment]
Here it is: https://github.com/hotmeteor/spectator/pull/54

Truth be told, before I reworked the route parameter parts I'm not sure URL matching was actually working that well. So it probably should have been doing this the whole time.

**Comment by bastien-phi** [comment]
@hotmeteor The patch works perfectly ! Thanks !

**Comment by hotmeteor** [comment]
Patched. Thanks!
