### ISSUE TITLE
Not compatible with oneOf/anyOf/allOf, not

### ISSUE THREAD

**Issue by bilfeldt** [hotmeteor/spectator#58]
It is possible to use the `oneOf`, `anyOf` or `allOf` notation in OpenAPI 3.0 Schemas as described in the [official documentation here](https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/) when describing requests/responses, but this causes a problem when trying to compare the schema.

The original error was
```
The data (string) must match the type: object 
```

Now this is caused by [src/Validation/RequestValidator.php#L116](https://github.com/hotmeteor/spectator/blob/820e3ebf4e5e14042b0cd64d86feb74db29c90f8/src/Validation/RequestValidator.php#L116):

```php
if ($jsonSchema->type === 'object' || $jsonSchema->type === 'array') { ...
```

where we also need to check for these type of schemas:

```php
if ($jsonSchema->type === 'object' || $jsonSchema->type === 'array' || $jsonSchema->oneOf || $jsonSchema->allOf || $jsonSchema->anyOf) { ...
```

Making this change causes the body to be converted correctly, but the next issue arising is that the `type` property seems to be required as it failed with the validation exception of:
```
The required properties (type) are missing
```

It seems that the codebase is not capable of handling the oneOf/anyOf/allOf cases but I have not been able to figure out if this is a quick fix or if the codebase is tightly coupled to the requirement of a `type`.

**Comment by hotmeteor** [comment]
Ya this is a known limitation, we've hit it as well in our own API testing. It's actually a shortcoming in the underlying parsing library.

When I find time to dig on it a bit more I will and update here.

**Comment by hotmeteor** [comment]
@bilfeldt OK, I have a branch I'm working on that provides support for `anyOf` and `oneOf` (`allOf` is still not working). 

However, iIt appears that in order to use `oneOf` you need to either defined `required` properties or set `additionalProperties: false`. The [`oneOf` documentation](https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/) doesn't have this, but this is in error. You can find more details in this thread here: https://github.com/stoplightio/spectral/issues/1482#issuecomment-839165633

**Comment by bilfeldt** [comment]
> @bilfeldt OK, I have a branch I'm working on that provides support for `anyOf` and `oneOf` (`allOf` is still not working).
> 
> However, iIt appears that in order to use `oneOf` you need to either defined `required` properties or set `additionalProperties: false`. The [`oneOf` documentation](https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/) doesn't have this, but this is in error. You can find more details in this thread here: [stoplightio/spectral#1482 (comment)](https://github.com/stoplightio/spectral/issues/1482#issuecomment-839165633)

Dear @hotmeteor thanks for taking the time to look at this. Do you have a branch which I should have a look at? The least I can do is test if this solves the issues I have been facing with this.

**Comment by hotmeteor** [comment]
@bilfeldt Try this one: https://github.com/hotmeteor/spectator/pull/59
