### ISSUE TITLE
basePaths / server URLs

### ISSUE THREAD

**Issue by philsturgeon** [hotmeteor/spectator#88]
Got an interesting situation here where an API has a global URL (not my choice).

```
servers:
  - url: 'https://api.protect.earth/v1'
    description: Production
```

In my tests I'm doing 

```
it('returns a valid record', function () {
    $this->getJson("/v1/orgs/{$this->uuid}")
        ->assertValidRequest()
        ->assertValidResponse(200);
});
```

Then Spectator is saying `  Path [GET /v1/orgs/{orgUuid}] not found in spec.`

Fair enough! Can I teach it to strip the prefix, or something? I don't want to change the OpenAPI to use /v1 in all the paths because its part of the server URL not the path.

Will buy you some coffeess if you can sort this out, it's for a blog posts I'm doing on [apisyouwonthate.com](https://www.apisyouwonthate.com)! 🙌🏻

**Comment by jarrodparkes** [comment]
Could you simply adjust the test to drop the `v1` prefix?

```php
$this->getJson("/orgs/{$this->uuid}")
```

Or, I think you can add a path prefix in the `spectator.php` config file:

```php
    /*
    |--------------------------------------------------------------------------
    | Paths
    |--------------------------------------------------------------------------
    |
    | Configure path defaults, like prefixes.
    |
    */

    'path_prefix' => 'v1',
```

Would that solve your problem?

**Comment by philsturgeon** [comment]
If I drop v1 from the test it will return a 404 as that URL does not existing in Laravel.

I tried every combination I could think of:

| v1 in test  | v1 in path param | v1 in OpenAPI | Outcome Test 
| ------------- | ------------- | ------------- | ------------- |
| ❌ | ❌ | ❌ | ❌
| ✅ | ❌ | ✅ | ✅
| ❌ | ✅ | ❌ | ❌
| ❌ | ✅ | ✅ | ❌

It did work when I put v1 in the test and in the openapi path but that's not the good outcome, and that's not being helped by path_prefix.

Whenever I used path_prefix I am seeing this debug in test output:

```
GET http://localhost/orders/3d1fe77d-b190-3742-a38b-3a15f7f4e009
```

It looks like the path prefix is not being used?

**Comment by hotmeteor** [comment]
@philsturgeon Thanks for the report, looking at this.

**Comment by hotmeteor** [comment]
@philsturgeon Here's my mock spec:

```yaml
openapi: 3.0.0
info:
  title: Global.v1
  version: '1.0'
servers:
  - url: 'https://api.protect.earth/v1'
    description: Production
paths:
  /orgs/{orgUuid}:
    get:
      summary: Get org
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  uuid:
                    type: string
                  name:
                    type: string
      operationId: get-org
      parameters:
        - schema:
            type: string
            format: uuid
          name: orgUuid
          in: path
          required: true
components:
  schemas: {}
```
And either of these setups work:
```php
public function test_uses_global_path()
{
    Config::set('spectator.path_prefix', 'v1');

    Spectator::using('Global.v1.yaml');

    $uuid = (string) Str::uuid();

    Route::get('/v1/orgs/{orgUuid}', function () use ($uuid) {
        return [
        'id' => 1,
        'uuid' => $uuid,
        'name' => 'My Org',
    ];
    })->middleware(Middleware::class);

    $this->getJson("/v1/orgs/{$uuid}")
    ->assertValidRequest()
    ->assertValidResponse(200);
}
```
or
public function test_uses_global_path()
{
    Spectator::setPathPrefix('v1')->using('Global.v1.yaml');

    $uuid = (string) Str::uuid();

    Route::get('/v1/orgs/{orgUuid}', function () use ($uuid) {
        return [
        'id' => 1,
        'uuid' => $uuid,
        'name' => 'My Org',
    ];
    })->middleware(Middleware::class);

    $this->getJson("/v1/orgs/{$uuid}")
    ->assertValidRequest()
    ->assertValidResponse(200);
}
```
However, seems like it would be advantageous for the package to be a little smarter in determining the prefix if it exists. I'll look and see if this can be improved.

**Comment by philsturgeon** [comment]
I wonder if the leading slash, or maybe the `Route::prefix()` is causing the different outcomes here? 

```
Route::prefix('v1')->group(function () {
    Route::get('/orgs/{organization}', [OrgController::class, 'fetch']);
    Route::get('/orders/{order}', [OrdersController::class, 'fetch']);
});
```

**Comment by K2ouMais** [comment]
I am having a similar issue with this package.

I want to test the ```/api/health``` like this.

```php
    public function testHealthResponseAgainstOpenapiSpecification()
    {
        Spectator::using(resource_path('openapi/myapi.json'));

        $response = $this->getJson('/api/health');

        $response->assertValidResponse(200);
    }
```

In my openAPI file the path is just ```/health```...

How can I get around this?

Thanks in advance

**Comment by bastien-phi** [comment]
For documentation :
```php
    public function testHealthResponseAgainstOpenapiSpecification()
    {
        Spectator::setPathPrefix('api')->using(resource_path('openapi/myapi.json'));

        $response = $this->getJson('/api/health');

        $response->assertValidResponse(200);
    }
   ```
