### ISSUE TITLE
assertingValidRequest even when not expected

### ISSUE THREAD

**Issue by philsturgeon** [hotmeteor/spectator#92]
Hey, I really like this tool, sorry to keep finding problems, but I'm working on an article for it. 🙌🏻 

So I've got a test which makes sure invalid URLs show a 404 and matches the defined schema (I want to see :Problem JSON not awkward backtraces or 500s right?)

The test was this:

```
it('returns a 404 for invalid record', function () {
    $this->getJson("/v1/orders/nonsense")
        ->assertValidResponse(404);
});
```

I get the "Invalid nested style tag found error" which was meant to have been got rid of, but isn't quite dead yet (#90). 

```
  • Tests\Feature\OrderTest > it returns a 404 for invalid record
   ErrorException

  Incorrectly nested style tag found.

  at tests/Feature/OrderTest.php:42
     38▕ });
     39▕
     40▕ it('returns a 404 for invalid record', function () {
     41▕     $this->getJson("/v1/orders/nonsense")
  ➜  42▕         ->assertValidResponse(404);
     43▕ });
     44▕
     45▕ it('returns a valid record', function () {
     46▕     $this->getJson("/v1/orders/{$this->uuid}")

  1   tests/Feature/OrderTest.php:42
      Illuminate\Testing\TestResponse::__call()
```

Anyhow, this isn't about the error message, its about the problem. When I add a dump() I see the issue is actually down to `nonsense` not being a valid UUID... but I've not used assertValidRequest() so why is it concerned about that?

```
{#2677
  +"exception": "Spectator\Exceptions\RequestValidationException"
  +"message": """
    ---\n
    \n
    \e[0;37;3mThe data must match the 'uuid' format\e[0m\n
    \n
    \e[0;37;mstring\e[0m <== \e[0;31;mThe data must match the 'uuid' format\e[0m\n
    \n
    """
  +"specErrors": array:1 [
    0 => "The data must match the 'uuid' format"
  ]
}
```

I can fix it by using some randomly generated UUID, any string in the right format basically.

```
it('returns a 404 for invalid record', function () {
    $this->getJson("/v1/orders/53d4faeb-e046-4ab1-91ff-6b6e35c4c052")
        ->assertValidResponse(404);
});
```

This is not going to be a blocker because I can just use this random string, but I thought you might like to know that this is happening because it suggests something odd is going on internally! 

Anyhow if I can bribe you with a coffee or 50 to fix this, or donate to a climate action charity of your choosing, I'd be happy to support your work on this. I'd love to be able to confidently recommend this tool to folks but this and #90 and #88 is causing me to pause for now.

**Comment by jarrodparkes** [comment]
Hey @philsturgeon 👋 

I'm going to guess you are seeing this behavior because Spectator, in order to try and validate the response, performs its entire validation process behind the scenes. I need to confirm this.

It may be the case that we will need some sort of `skipValidRequest`, or minimally, to inform users of this behavior.

#90 and #88 are on our radars too 👍 

Best,
Jarrod

**Comment by hotmeteor** [comment]
What @jarrodparkes said. I'll poke around on these again today. Were you able to review my comments on #88 and #90?

**Comment by philsturgeon** [comment]
Thank you for the response and the insight. The technical implementation aside, it seems most logical for skipValidRequest to be the default behavior, and assertValidRequest() to be called if you'd like to validate the request.

It could be that you do indeed perform the validation on everything, then strip out request related feedback if they've not asked for feedback on the request?

**Comment by hotmeteor** [comment]
@philsturgeon I can't be 100% sure without seeing your code, but I think what you're seeing is possibly based on the way your test is structured. I was able to get the expected results with this test:

```php
public function test_response_without_request_validation()
{
    Spectator::using('Test.v1.json');

    $uuid = (string) Str::uuid();

    Route::get('/posts/{postUuid}', function ($postUuid) use ($uuid) {
        return (string) $postUuid === $uuid
            ? response()->json([
                'id' => 1,
                'title' => 'My Blog Post',
            ], 200)
            : abort(404);
    })->middleware(Middleware::class);

    $this->getJson("/posts/{$uuid}")
        ->assertValidResponse(200);

    $invalidUuid = (string) Str::uuid();

    $this->getJson("/posts/{$invalidUuid}")
        ->assertValidResponse(404);

    $this->getJson('/posts/nonsense')
        ->assertValidResponse(404);
}
```
However, within your app test suite that could be different when it comes to route model binding. Can you try going to `SpectatorServiceProvider`, line 39, and changing:
```php
    protected function registerMiddleware()
    {
        $this->app[Kernel::class]->prependMiddlewareToGroup('api', Middleware::class);
    }
```
to
```php
    protected function registerMiddleware()
    {
        $this->app[Kernel::class]->appendMiddlewareToGroup('api', Middleware::class);
    }
```

**Comment by philsturgeon** [comment]
I think we're doing different things. 

```
$invalidUuid = (string) Str::uuid();
```

That is a valid UUID. Try changing it to this:

```
$invalidUuid = "literally anything else";
```

Is that giving you request errors now?

**Comment by hotmeteor** [comment]
I think you'd be doing a request test in that case, right? Making sure the URL has the right properties?

**Comment by philsturgeon** [comment]
It’s not a request test. I should not need to make the request pass every single possible validation if I’m not testing to see if it’s a valid request. 

The era api would respond with a 404 when I request /Foo/nonsense and I’m testing the response. The validity of the request isn’t relevant at all.

**Comment by philsturgeon** [comment]
In case I’m being confusing, I should only be told about the validity of the request if I ask to assert valid request. Otherwise, I shouldn’t see anything about it.

**Comment by hotmeteor** [comment]
Sorry, not trying to be difficult. I get what you're looking for, but I don't think it's possible with how you're testing.

Spectator is using the Laravel routing system to hit endpoints. That can be an existing route, or it can be a mock one (like in my test examples). Since it's using the router it's going to trigger the normal exceptions that any invalid request would trigger, if the values don't match.

In the case of a mock route I can choose to adhere to or ignore any route parameter rules I want, as well as return any status code I want. But with a "real" route, it'll kick in route model binding if applied, or whatever other validation is going on.

Therefore... if we mute request validation because you only want to test the shape of your 404 response, it's impossible without a mock route. 404's are triggered on the request. So you either need to:

- Test a 404 response using a request test with an actual route + invalid path
- Test a 404 response using either test and a mock route of your own design

Does this make sense?

**Comment by philsturgeon** [comment]
Laravel doesn’t know what the parameter schema validations are right? Only spectator knows that it’s format: uuid but Laravel hasn’t got a clue.

So if the exception is being thrown that it’s not a uuid, that has to be coming from spectator and not Laravel? And therefore it’s in your control to decide if you error or suppress?

**Comment by philsturgeon** [comment]
@ArondeParon nothing much for me to resolve as its just currently how Spectator works. there's a PR for testing the behavior, but it's unfinished. https://github.com/hotmeteor/spectator/pull/94

This is an excellent tool, and I hope this can be done to make it even excellenter.

**Comment by hotmeteor** [comment]
Hey team, sorry for the delay. I'm going to give it another go today to see if I can do something clever here, since this is clearly something multiple people are running into.

**Comment by hotmeteor** [comment]
> So if the exception is being thrown that it’s not a uuid, that has to be coming from spectator and not Laravel? And therefore it’s in your control to decide if you error or suppress?

@philsturgeon Ya this part I agree with for sure. I can't help if route model-binding fails, but it shouldn't care if it's actually a UUID or not.

**Comment by hotmeteor** [comment]
@ArondeParon @philsturgeon 

Ok, here's a test I've got that passes. Can you tell me what part I'm missing so I can be sure I'm testing it with your issue you're hitting?

```php
public function test_response_without_validating_route_model_binding()
{
    Spectator::using('Test.v1.json');

    $uuid = (string) Str::uuid();

    Route::get('/posts/{postUuid}', function ($postUuid) use ($uuid) {
        return [
            'id' => 1,
            'name' => 'My Org',
            'orders' => [[]],
        ];
    })->middleware(Middleware::class);

    $this->getJson("/posts/{$uuid}")
        ->assertValidResponse(200);

    $otherUuid = (string) Str::uuid();

    $this->getJson("/posts/{$otherUuid}")
        ->assertValidResponse(200);

    $this->getJson('/posts/123456')
        ->assertValidResponse(200);

    $this->getJson('/posts/nonsense')
        ->assertValidResponse(200);
}
```

**Comment by philsturgeon** [comment]
Brilliant! Can we add:

```
    $this->getJson("/posts/nonsense")
        ->assertValidResponse(404);
```

**Comment by hotmeteor** [comment]
Not sure I understand... why would that 404 in this scenario?

**Comment by philsturgeon** [comment]
Because it doesn't exist!

```php
<?php
use App\Models\Organization;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Spectator\Spectator;

uses(RefreshDatabase::class);

beforeAll(function () {
    $organization = Organization::factory()->create();
    $this->uuid = $organization->organization_uuid;

    // Add Spectator 👇
    Spectator::using('openapi.yaml');
});

it('returns a 404 for invalid record', function () {
    $this
        ->getJson("/orgs/does-not-exist")
        ->assertValidResponse(404);
});

it('returns a valid record', function () {
    $this
        ->getJson("/orgs/{$this->uuid}")
        ->assertValidResponse(200);
});
```

The point of this test is to a) make sure it returns the 200 and valid contract when something exists, and b) to make sure it returns a 400 and valid error contract if it does not exist. 

Instead of focusing on the response, it's giving me feedback on the validity of my request, which I have no asked for. 

More on the example over here: https://apisyouwonthate.com/blog/contract-testing-apis-laravel-php-openapi

**Comment by philsturgeon** [comment]
Your test is hardcoded so it will always return a response and a 200, but real APIs are not like that. They will need to test the sad path as well as the happy path, and your test could reflect that to help folks ensure their error messages are formatted correctly too.

**Comment by hotmeteor** [comment]
Ah ok... this is exactly what I've been looking for. The previous iteration of the test example had what you're talking about, but I guess I was confused if that was an issue. Let me rework my example quick.

**Comment by hotmeteor** [comment]
Is this what you mean?
```php
public function test_response_without_validating_route_model_binding()
{
    Spectator::using('Test.v1.json');

    $uuid = (string) Str::uuid();

    Route::get('/posts/{postUuid}', function ($postUuid) use ($uuid) {
        if ($postUuid !== $uuid) {
            abort(404);
        }

        return [
            'id' => 1,
            'name' => 'My Org',
            'orders' => [[]],
        ];
    })->middleware(Middleware::class);

    $this->getJson("/posts/{$uuid}")
        ->assertValidResponse(200);

    $otherUuid = (string) Str::uuid();

    $this->getJson("/posts/{$otherUuid}")
        ->assertValidResponse(404);

    $this->getJson('/posts/123456')
        ->assertValidResponse(404);

    $this->getJson('/posts/nonsense')
        ->assertValidResponse(404);
}
```

**Comment by philsturgeon** [comment]
Yeah that'll work! Thank you

**Comment by hotmeteor** [comment]
Ok because that passes.

**Comment by hotmeteor** [comment]
https://github.com/hotmeteor/spectator/pull/94

**Comment by philsturgeon** [comment]
Weird! It blows up in my face over here and for others. I wonder if there's a difference in the simple implementation of the test vs the way its done with Pest, or proper controllers, or something else.

**Comment by hotmeteor** [comment]
Ya I believe you, there's gotta be something else at play. The only thing I can think is that Laravel is barfing on a non-integer when it expects one to resolve the route. If you're using UUIDs though I assume you've got custom binding so that wouldn't do it. Hmm...

**Comment by philsturgeon** [comment]
@hotmeteor if you fancy jumping on a zoom call sometime I'd be happy to work together to try and track it down? Use this link and just pretend its about the climate crisis so its free. 😆

**Comment by hotmeteor** [comment]
Awesome, I'll find some time for us this week.

**Comment by joshuafranks** [comment]
Did you guys get anywhere with this? I'm facing a similar issue when testing for validation errors. 

```
/**
 * @test
 */
public function it_returns_422_if_email_is_missing()
{
    // given
    Customer::factory()->create([
        'email' => 'joshua.franks@lovehomeswap.com',
        'password' => Hash::make('password'),
    ]);

    // when
    $response = $this->postJson(route('authenticate'), [
        'email' => null,
        'password' => 'password',
        'device_name' => 'iPhone 11 Pro Max',
    ]);

    // then
    $response->assertValidResponse(422);
}
```

In this scenario, I want to assert that my API kicks back a 422 response in line with my specification. Instead, I end up with this failure:

```
There was 1 error:

1) Tests\Feature\Api\Authentication\Controllers\AuthenticateUserControllerTest::it_returns_422_if_email_is_missing
ErrorException: Expected status code 422 but received 400.
Failed asserting that false is true.

/var/www/core_api/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php:124
/var/www/core_api/vendor/laravel/framework/src/Illuminate/Testing/TestResponse.php:1664
/var/www/core_api/vendor/hotmeteor/spectator/src/Assertions.php:83
/var/www/core_api/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php:124
/var/www/core_api/vendor/laravel/framework/src/Illuminate/Testing/TestResponse.php:1664
/var/www/core_api/tests/Feature/Api/Authentication/Controllers/AuthenticateUserControllerTest.php:85
```

Upon further inspection, I can see that it's failing because Spectator is attempting to validate the request:

```
{
  "exception": "Spectator\\Exceptions\\RequestValidationException",
  "message": "---\n\n\u001b[0;37;3mThe properties must match schema: email\nThe data (null) must match the type: string\u001b[0m\n\n\u001b[0;37;mobject++\u001b[0m <== \u001b[0;31;mThe properties must match schema: email\u001b[0m\n\u001b[0;37;m    email*: string\u001b[0m <== \u001b[0;31;mThe data (null) must match the type: string\u001b[0m\n\u001b[0;32;m    password*: string\u001b[0m\n\u001b[0;32;m    device_name*: string\u001b[0m\n\n",
  "specErrors": [
    "The properties must match schema: email",
    "The data (null) must match the type: string"
  ]
}
```

This is not the behaviour I'd expect to see here.

**Comment by philsturgeon** [comment]
Didn't help that I didn't put the link in that previous comment. https://calendly.com/philsturgeon/climate

**Comment by philsturgeon** [comment]
I've just noticed that even when I don't use assertValidResponse I'm still having spectator tell me that an intentionally invalid request is invalid. this means I have no way to test my 4xx responses.

```

it('returns a 422 for invalid parameters', function ($data) {

    // TODO cannot use spectator to test invalid responses because if request is valid spectator
    // will give its own 400 errors instead of our 422 errors.
    // https://github.com/hotmeteor/spectator/issues/92
    // ->assertValidResponse(422);

    $this
        ->withToken($this->api_key)
        ->postJson('/v1/orders', $data)
        ->dump()
        ->assertStatus(422)
        ->assertJson([
            'type' => 'foo',
            'title' => 'foo',
            'status' => 'foo',
            'detail' => 'foo',
            'instance' => true,
        ]);

})->with([
    [[]],
    [['orderedTrees' => null]],
    [['orderedTrees' => -1]],
    [['orderedTrees' => 'tree']],
]);

```

@hotmeteor is there any chance I can invite you to the Protect Earth API private repo so you can just run `sail test` and play around with this? I'd love to increase the testing on this API.

**Comment by hotmeteor** [comment]
Hey all, sorry for the radio silence.

Coming back at this with somewhat fresh eyes, it seems like Spectator needs to have APIs available that can disable portions of the validation process, similar to what was mentioned here: https://github.com/hotmeteor/spectator/issues/107

I'll put together a branch now and y'all can try it.

**Comment by hotmeteor** [comment]
Alright @philsturgeon, @joshuafranks, etc., give this branch a try: https://github.com/hotmeteor/spectator/pull/110

**Comment by philsturgeon** [comment]
Thanks for this @hotmeteor, I have tested it works as you've  demonstrated.

I gotta be honest though, it feels weird to turn off functionality that I have specifically not asked to be run. Introducing `Spectator::skipRequestValidation()` to tell it not to do something I am not asking it to do is the opposite of how I'd expect things to go.

It feels like `->assertValidRequest()` should only assert the request is valid when I ask it to, just as `->assertValidResponse(422)` should only assert the response is valid because I asked it to. 

```
it('returns a 422 for invalid parameters', function ($data) {
    Spectator::skipRequestValidation();

    $this
        ->withToken($this->api_key)
        ->postJson('/orders', $data)
        ->assertValidResponse(422);

})->with([
    [[]],
    [['orderedTrees' => null]],
    [['orderedTrees' => -1]],
    [['orderedTrees' => 'tree']],
]);
```

But, this does at least get these tests working, so thats good! :D

**Comment by hotmeteor** [comment]
Ya that makes sense. The reason is because the validation is run at request/response time, but assertions are _after_ the response.

I guess one way to get around this could be to "cache" the validation and then only report what the developer wants to see. But at least now we have a handle on what's doing this.

**Comment by philsturgeon** [comment]
> I guess one way to get around this could be to "cache" the validation and then only report what the developer wants to see. But at least now we have a handle on what's doing this.

@hotmeteor that's exactly what I'm thinking! Yeah, you wanna build up "problems" then decide if they "matter' based on what the test is saying amtters, right? 

Great that progress is here and I'm definitely not complaining, I just want this package to reach its fullpotential and be epic. I'm blogging about it already https://apisyouwonthate.com/blog/contract-testing-apis-laravel-php-openapi but there's bigger trumpets I can blow! :D

**Comment by joshuafranks** [comment]
I agree with Phil, it feels weird that we have to explicitly disable something we haven't asked for; I'll take a look under the hood this weekend and see if I can come up with something. Happy to pair up with you some time if you fancy it @hotmeteor!

**Comment by hotmeteor** [comment]
OK gents, I've done it.

Check out the [skip-request-validation](https://github.com/hotmeteor/spectator/tree/skip-request-validation) branch again, you should have full control over what you want validated. I also made some other cleanups.

**Comment by philsturgeon** [comment]
Brilliant! I've checked and it works, removing `assertValidRequest()` hides errors with invaldi requests! :D 

Strangely I am getting errors that `3eefa532-38d3-37cc-a434-e5b60a6c205f` is not a valid UUID which I wasn't getting before, but that could be something else. The uuid is being made with `$this->faker->uuid()` if that helps.

**Comment by philsturgeon** [comment]
Oh and a massive thank you for doing that! This is a great tool and I'm exfited to see it progress. If you've got a sponsor link I'll chuck a few beverages in there.
